### ISSUE TITLE
Blank error on `ctrl + click`

### ISSUE THREAD

**Issue by CharlSteynberg** [claytonrcarter/hyperclick-php#10] opened 2019-11-27 10:40 UTC
This package does not work. I've tried the "composer optional autoload" as well, all it renders when `ctrl + click` (-on anything) is:
> `Error: `

... no description.<br>
Tried restarting **Atom** .. still the same.

**Comment by claytonrcarter** [comment] 2019-11-27 11:06
Thanks, but closing as a duplicate of the comment you left on #9

**Closed as completed by claytonrcarter** 2019-11-27 11:06 UTC
